### ISSUE TITLE
Implement GCE wrappers to enable a SOLVCON parallel cluster.

### ISSUE THREAD

**Issue by tai271828** [solvcon/solvcon-gce#10]
In the recent SOLVCON source https://github.com/solvcon/solvcon/commit/b11b5a52920634e1b40f51f5642b30d755258058, we have fixed several issues including to bring remote computing feature back https://github.com/solvcon/solvcon/issues/135, the pickling issue https://github.com/solvcon/solvcon/pull/168 , and also add a cluster feature test case https://github.com/solvcon/solvcon/commit/b11b5a52920634e1b40f51f5642b30d755258058. It is time to establish the cloud computing feature for SOLVCON based on the above infrastructure. I am planing to implement GCE wrappers so users and developers could build SOLVCON run-time or development environment in a very easy and quick way with GCE.

The definition of done for this goal is :
- [ ] bootstrap scripts to enable a node to be NFS master node.
- [ ] bootstrap scripts to enable a node to be client node.
- [ ] bootstrap scripts to enable a node to be a SOLVCON service node. Issue https://github.com/solvcon/solvcon-gce/issues/6 is a part of this task. 
- [ ] wrappers are able to issue commands to bootstrap the above nodes.
- [ ] the above implementation could pass this 2-node cluster test https://github.com/solvcon/solvcon/commit/b11b5a52920634e1b40f51f5642b30d755258058.

Once this issue is completed, I am going to extend the wrappers to enable 3 or more nodes on GCE. This 3-nodes milestone is too large,so it is better to use another issue report to trace it. Let's focus on the 2-node infrastructure first.

This roadmap is still at the stage of blueprint. Any comment is welcome.

**Comment by yungyuc** [comment]
This is a bucket of many tasks.  I think this issue should be turned into a project.  Close.

**Comment by tai271828** [comment]
Trace this issue with this project https://github.com/solvcon/solvcon-gce/projects/1 instead.

**Comment by yungyuc** [comment]
We should stop using this issue to check in code as it is closed.  @tai271828 could you divide it up and file new issues?

**Comment by tai271828** [comment]
The above activities of commit messages are redundant when I was rebasing the commit log for creating PR. Sorry for the spam. Please ignore them.

Project 1 https://github.com/solvcon/solvcon-gce/projects/1 is used to replace this issue. I move the same description of this issue to be the description of Project 1. Divide it into smaller issues and include these issues in project 1 is a good idea. I will do it.

**Comment by yungyuc** [comment]
But as you mentioned you cannot change the project without a write permission.  It seems to be a show stopper.  Should we still use project?
