### ISSUE TITLE
Add test case instruction to bootstrap a SOLVCON parallel cluster on GCE.

### ISSUE THREAD

**Issue by tai271828** [solvcon/solvcon-gce#12]
We have already merged this PR https://github.com/solvcon/solvcon-gce/pull/11 to make solvcon-gce has feature to bootstrap such cluster. The test case instruction in the PR description is useful, and it will be better to add it into somewhere like script as remark.

**Comment by yungyuc** [comment]
Any update?

**Comment by tai271828** [comment]
Please refer to PR https://github.com/solvcon/solvcon-gce/pull/14/files .

**Comment by tai271828** [comment]
This commit is trivial and does not really touch any implementation of the other components. The risk of regression is low, so I will self-approve to merge this PR.

**Comment by tai271828** [comment]
PR is merged. Close this issue.
