### ISSUE TITLE
Survey the way to share NFS when bootstrapping SOLVCON parallel cluster.

### ISSUE THREAD

**Issue by tai271828** [solvcon/solvcon-gce#13]
We have already merged this PR https://github.com/solvcon/solvcon-gce/pull/11 to make solvcon-gce has feature to bootstrap such cluster. However it is a very fresh prototype. A topic worth working on is how to share working directory and SSH information. See this for the context as well: https://github.com/solvcon/solvcon-gce/pull/11#r78276601

**Comment by yungyuc** [comment]
I suppose the survey won't have a direct action item with code.  The issue should be turned into a project item (project is a new feature of github).  I am closing the issue.

**Comment by tai271828** [comment]
Trace this issue with this project https://github.com/solvcon/solvcon-gce/projects/1 instead.
