### ISSUE TITLE
Solution survey - how Kubernetes organize the instances creation.

### ISSUE THREAD

**Issue by tai271828** [solvcon/solvcon-gce#17]
This issue is raised during the discussion of this PR thread https://github.com/solvcon/solvcon-gce/pull/16#discussion_r79971553 . This PR has many hard-coded for instance naming. Maybe we could refer to Kubernetes and implement a better way for SOLVCON-GCE.

This issue is a part of Project 1 https://github.com/solvcon/solvcon-gce/projects/1 .

Kubernetes is an open-source platform for automating deployment, scaling, and operations of application containers across clusters of hosts, providing container-centric infrastructure. 
http://kubernetes.io/docs/whatisk8s/

**Comment by yungyuc** [comment]
I'd like to try tracking non-issues using project.  I will close this issue.
