### ISSUE TITLE
Conda cache bucket name cannot be hard-coded: Google cloud storage uses a global namespace

### ISSUE THREAD

**Issue by yungyuc** [solvcon/solvcon-gce#3]
The conda cache bucket now uses a hard-coded name.  It prevents the script from being used to another project, because the bucket name uses a global namespace in GCP.  When creating a conda cache bucket, GS shows the following errors:

```
updating: heapdict-1.0.0-py27_1.tar.bz2
updating: backports-1.0-py27_0.tar.bz2
updating: matplotlib-1.5.1-np110py27_0.tar.bz2
Building synchronization state...
Caught non-retryable exception while listing gs://conda-packages/: AccessDeniedException: 403 Forbidden
CommandException: Caught non-retryable exception - aborting rsync
```

Therefore, `gce-create-instance` and `gce-prepare-conda-packages` may not use the hard-coded bucket name.  Maybe the scripts should use the project ID as part of the bucket name to make it unique.

This issue was mentioned in https://github.com/solvcon/solvcon-gce/issues/2#issuecomment-232212859 .

**Comment by tai271828** [comment]
If we want to use the project ID as part of the bucket name, we have to figure out how to create the bucket and its name via commands instead of users's GUI. Before implementing this, I have proposed a version of code to parse a customized bucket name option for gstart.

**Comment by yungyuc** [comment]
Conda cache bucket name now has project ID in it.  Close issue by f63cc8e.
