### ISSUE TITLE
bootstrap-gce.sh should prepare necessary packages and SOLVCON source to run SOLVCON

### ISSUE THREAD

**Issue by tai271828** [solvcon/solvcon-gce#6]
Currently bootstrap-gce.sh only prepares fresh miniconda for instances. It will be great to prepare the other packages for SOLVCON. The following items will be added to gstart as options, and the default values of all of them are **No** to control the GCE cost.
- [ ] install packages via the ready-to-use miniconda
- [ ] install packages which are not available from the ready-to-use miniconda
- [ ] fetch SOLVCON source
- [ ] set up environment variables to use SOLVCON source
- [ ] build and install SOLVCON

**Comment by yungyuc** [comment]
An issue having many tasks like this should be turned into a project.  So I close this one.

**Comment by yungyuc** [comment]
Any update for this issue?

**Comment by tai271828** [comment]
Yes, this commit https://github.com/solvcon/solvcon-gce/commit/36ca338fd3c89e44805c05eb2fc750759258e245 actually has implemented part of this topic. However, I agree with you. Let's trace this with a project. I will open the project later.

**Comment by tai271828** [comment]
Trace this issue with this project https://github.com/solvcon/solvcon-gce/projects/1 instead.
